version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    files:
    -'s3://portfolio-artifacts-3007/pipeline-loading-sou/BuildArtif/k5WVSDv'
    - echo "Deployed to S3"
artifacts:
  files:
    - '**/*'
