version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    - echo "Deployed to S3"
artifacts:
  files:
    - 's3://portfolio-artifacts-3007/pipeline-loading-sou/BuildArtif/Daj8m27'
