version: 0.2
os: linux
phases:
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    files:
  - source: /index.html
    destination: /var/www/html/
    - echo "Deployed to S3"
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

artifacts:
  files:
    - '**/*'
